services:
  magicmirror:
    container_name: magicmirror
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    environment:
      - MM_SCENARIO=server
    volumes:
      - ./mounts/config:/opt/magic_mirror/config
      - ./mounts/modules/MMM-WindCompass:/opt/magic_mirror/modules/MMM-WindCompass
    ports:
      - "8080:8080"
